/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface LiquidityManagerInterface extends utils.Interface {
  contractName: "LiquidityManager";
  functions: {
    "burnAddress()": FunctionFragment;
    "createPair(address,address,address)": FunctionFragment;
    "getLiquidityCreated(address,address,address)": FunctionFragment;
    "getPairAddress(address,address,address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "burnAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "createPair",
    values: [string, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getLiquidityCreated",
    values: [string, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getPairAddress",
    values: [string, string, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "burnAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "createPair", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getLiquidityCreated",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPairAddress",
    data: BytesLike
  ): Result;

  events: {};
}

export interface LiquidityManager extends BaseContract {
  contractName: "LiquidityManager";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: LiquidityManagerInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    burnAddress(overrides?: CallOverrides): Promise<[string]>;

    createPair(
      _routerAddress: string,
      _tokenA: string,
      _tokenB: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    getLiquidityCreated(
      _routerAddress: string,
      _tokenA: string,
      _tokenB: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    getPairAddress(
      _routerAddress: string,
      _tokenA: string,
      _tokenB: string,
      overrides?: CallOverrides
    ): Promise<[string]>;
  };

  burnAddress(overrides?: CallOverrides): Promise<string>;

  createPair(
    _routerAddress: string,
    _tokenA: string,
    _tokenB: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  getLiquidityCreated(
    _routerAddress: string,
    _tokenA: string,
    _tokenB: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  getPairAddress(
    _routerAddress: string,
    _tokenA: string,
    _tokenB: string,
    overrides?: CallOverrides
  ): Promise<string>;

  callStatic: {
    burnAddress(overrides?: CallOverrides): Promise<string>;

    createPair(
      _routerAddress: string,
      _tokenA: string,
      _tokenB: string,
      overrides?: CallOverrides
    ): Promise<string>;

    getLiquidityCreated(
      _routerAddress: string,
      _tokenA: string,
      _tokenB: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    getPairAddress(
      _routerAddress: string,
      _tokenA: string,
      _tokenB: string,
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {};

  estimateGas: {
    burnAddress(overrides?: CallOverrides): Promise<BigNumber>;

    createPair(
      _routerAddress: string,
      _tokenA: string,
      _tokenB: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    getLiquidityCreated(
      _routerAddress: string,
      _tokenA: string,
      _tokenB: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getPairAddress(
      _routerAddress: string,
      _tokenA: string,
      _tokenB: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    burnAddress(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    createPair(
      _routerAddress: string,
      _tokenA: string,
      _tokenB: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    getLiquidityCreated(
      _routerAddress: string,
      _tokenA: string,
      _tokenB: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getPairAddress(
      _routerAddress: string,
      _tokenA: string,
      _tokenB: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
